# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-02 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_role', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('uid', models.CharField(max_length=20)),
            ],
        ),
    ]
